
from pydantic import BaseModel, Field, constr
from typing import List, Optional, Dict, Any

NonEmptyStr = constr(strip_whitespace=True, min_length=1)

class AnalyzeRequest(BaseModel):
    user_input: NonEmptyStr = Field(..., description="User's natural language input about movies.")

class RetrieveRequest(BaseModel):
    preferences: Dict[str, Any] = Field(..., description="Preference data generated by the analyzer.")

class OrchestrateRequest(BaseModel):
    user_input: NonEmptyStr
    schedule_text: Optional[str] = Field(None, description="User's schedule or availability text.")

class ScheduleRequest(BaseModel):
    movies: List[Dict[str, Any]] = Field(..., description="List of movie data dictionaries.")
    schedule_text: NonEmptyStr
